packages:
  - .

allowBuilds:
  esbuild: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@11.15.1

overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

trustPolicy: no-downgrade
