packages:
  - .

allowBuilds:
  esbuild: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@12.10.0
  - source-map-js@1.2.2

overrides:
  semver: '>=7'
  source-map-js@>=1.0.0 <1.2.2: ^1.2.2

trustPolicy: no-downgrade
