overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': ^24
  ajv@<8.18.0: '>=8.18.0'
  eslint: ^9
  eslint>ajv: ^6.12.4
  minimatch@<10.2.1: '>=10.2.1'
