name: Build and Test
 
on:
  pull_request:
    branches:
      - main
  push:
    branches:    
    - main 

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
      name: Install pnpm

    - name: lint
      run: pnpm lint

    - name: Build
      run: pnpm build
